version: '3.7'

services:
  
  todo-web:
    image: diamolkor/ch06-todo-list
    ports:
      - "8020:80"
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat
