version: "3.7"

services:
  todo-web:
    image: diamolkor/ch21-todo-list
    ports:
      - 8080:80
    networks:
      - app-net

  todo-db:
    image: diamolkor/postgres:11.5
    networks:
      - app-net

  message-queue:
    image: diamolkor/nats
    ports:
      - "8222:8222"
    networks:
      - app-net

  save-handler:
    image: diamolkor/ch21-save-handler
    networks:
      - app-net

networks:
  app-net:
