version: "3.7"

services:
  todo-web:
    image: diamolkor/ch06-todo-list:v2
    ports:
      - 8089:80
    environment:
      - Database:Provider=Sqlite

secrets:
  todo-db-connection:
    file: empty.json
