version: "3.7"

services:
  todo-web:
    image: diamolkor/ch06-todo-list
    ports:
      - 80
    environment:
      - Database:Provider=Sqlite
    networks:
      - app-net

networks:
  app-net:
